[project]
name = "day-two"
version = "0.1.0"
authors = [{ name = "ANURAG JAMANKAR", email = "anurag.jamankar.aj@gmail.com" }]
description = "Basic python Drills"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
