[project]
name = "day-four"
version = "0.1.0"
authors = [{ name = "ANURAG JAMANKAR", email = "anurag.jamankar.aj@gmail.com" }]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
